language: generic
os: osx

# https://docs.travis-ci.com/user/reference/osx/#macos-version
jobs:
  include:
    - osx_image: xcode12   # Catalina 10.15
    - osx_image: xcode11.3 # Mojave 10.14
    - osx_image: xcode10.1 # High Sierra 10.13

install:
  - brew cask install mactex-no-gui

script:
  - brew tap $TRAVIS_REPO_SLUG https://github.com/$TRAVIS_REPO_SLUG

  - |
    if [ "$TRAVIS_OSX_IMAGE" = 'xcode12' ]; then
      brew unlink python@3.8
    fi

  - brew install --only-dependencies lilypond
  - travis_wait brew install lilypond
  - brew test lilypond
