language: generic
os: osx

# https://docs.travis-ci.com/user/reference/osx/#macos-version
jobs:
  include:
    - osx_image: xcode12.2 # Catalina 10.15
    - osx_image: xcode11.3 # Mojave 10.14

install:
  - brew cask install mactex-no-gui

script:
  - brew tap $TRAVIS_REPO_SLUG https://github.com/$TRAVIS_REPO_SLUG

  - brew install --only-dependencies lilypond
  - travis_wait brew install lilypond
  - brew test lilypond
