name: CI

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]
        formula: [lilypond, abjad, ly]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install MacTeX
      run: brew install --cask mactex-no-gui
      if: ${{ matrix.formula == 'lilypond' }}

    - name: Create Homebrew tap
      run: brew tap $GITHUB_REPOSITORY $GITHUB_SERVER_URL/$GITHUB_REPOSITORY

    - name: Install dependencies
      env:
        FORMULA: ${{ matrix.formula }}
      run: brew install --only-dependencies $FORMULA

    - name: Install formula
      env:
        FORMULA: ${{ matrix.formula }}
      run: brew install --verbose $FORMULA

    - name: Test formula
      env:
        FORMULA: ${{ matrix.formula }}
      run: brew test --verbose $FORMULA

    - name: Uninstall formula
      env:
        FORMULA: ${{ matrix.formula }}
      run: brew uninstall $FORMULA
