name: CI

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - run: brew tap $GITHUB_ACTOR/lilypond

    - run: brew cask install mactex-no-gui

    - run: brew install --verbose lilypond

    - run: brew test --verbose lilypond

    - run: brew uninstall lilypond

    - run: brew install --HEAD --verbose lilypond

    - run: brew test --verbose lilypond
