name: CI

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - run: brew install --cask mactex-no-gui

    - run: brew tap $GITHUB_REPOSITORY $GITHUB_SERVER_URL/$GITHUB_REPOSITORY

    - run: brew install --only-dependencies --verbose lilypond
    - run: brew install --verbose lilypond
    - run: brew test --verbose lilypond

    - run: brew uninstall lilypond

    - run: brew install --HEAD --only-dependencies --verbose lilypond
    - run: brew install --HEAD --verbose lilypond
    - run: brew test --verbose lilypond
